### ISSUE TITLE
Problem when loading bfl logs

### ISSUE THREAD

**Issue by alorcamo** [BehaviorTree/Groot#48]
I have not been able to run a single log view. Everytime I get an assertion exception: `.../src/Groot/depend/BehaviorTree.CPP/include/behaviortree_cpp_v3/flatbuffers/flatbuffers.h:1988: flatbuffers::Verifier::Verifier(const uint8_t*, size_t, flatbuffers::uoffset_t, flatbuffers::uoffset_t, bool): Assertion `size_ < FLATBUFFERS_MAX_BUFFER_SIZE' failed.`

I have tried with the standard examples and some of my own. I have checked also the latest commit ccec93bad.

Using compilers: g++-7 (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
and g++-4.9.

Since no one else seems to have this issue, I wonder whether I am missing some obvious thing. Any help is greatly appreciated. 

ps.: Thanks for this awesome BT library with batteries included!

**Comment by facontidavide** [comment]
Hi, I need you to give me more information to reproduce this and fix it.

Can you please send me the log file?

**Comment by alorcamo** [comment]
Hi, here is a link: [bt_trace.fbl](https://we.tl/t-OkWep3XEEe)
let me know if you need anything else.

**Comment by Xeerot** [comment]
I encountered the same issue. It looks like the issue is from this line of code in [SidepanelReplay::loadLog](https://github.com/BehaviorTree/Groot/blob/ccec93badc81a7a6ceabd94969632dfc51b9c4ca/bt_editor/sidepanel_replay.cpp#L183). It should be using content.size() and not content.data() when generating the buffer size.
