### ISSUE TITLE
Problems building Groot

### ISSUE THREAD

**Issue by magi-dalmau** [BehaviorTree/Groot#50]
Hi, I'm trying to build (with catkin build) groot but I get this error: 

/usr/bin/ld: cannot find -lbehaviortree_cpp_v3
collect2: error: ld returned 1 exit status

I'm using ROS Kinetic in ubuntu 16.04 LTS

Any thoughts? 

Thank you very much in advance

**Comment by pauldinh** [comment]
@magi-dalmau I put in a [PR](https://github.com/BehaviorTree/Groot/pull/53) to address this if you wanted to test it.

**Comment by danem** [comment]
@pauldinh I was having the same problem. I've tried your fix, but I'm still getting a linker error.

I've tried installing behaviortree-cpp with apt (ie: `apt-get install ros-melodic-behavior-tree-cpp`) and building it with catkin.

**Comment by pauldinh** [comment]
@danem Can you verify what target(s) you're getting the linker error on? The possible targets are:

- `behavior_tree_editor`
- `Groot`
- `editor_test`
- `replay_test`

The output of `catkin build VERBOSE=1` could be helpful if you can / are allowed to post it.

Also, I neglected to mention my environment:

- 18.04 + ROS Melodic
- `catkin tools` (and not `catkin_make`) configured to use an install space [0]
- compiling `BehaviorTree.CPP` from source

(my `catkin build --get-env groot` looks similar to yours)

I'm compiling `BehaviorTree.CPP` from source because the latest ROS Melodic sync does not have [this commit](https://github.com/BehaviorTree/BehaviorTree.CPP/commit/43c003d3fe940e09302458784d498fb9ceaf4494). If I attempt to compile `Groot` using `ros-melodic-behaviortree-cpp-v3`, I get an error regarding `flatbuffers/stl_emulation.h`. That said, I temporarily modified the include_directories for Groot so it could find `flatbuffers/stl_emulation.h` (on `master`), got the linker error(s), switched to the PR branch, and did a `catkin clean && catkin build` and everything compiled successfully. I then uninstalled the `ros-melodic-behaviortree-cpp-v3` package and repeated the same with `BehaviorTree.CPP` from source (and undid the temporary `include_directories` change). Got the linker errors on `master` but they compiled on the PR branch.

I wouldn't be surprised if I'm missing something but I can't seem to reproduce the error on my end.

[0] I noticed I cannot do `rosrun groot Groot` using the install space. `BehaviorTree.CPP` is not configured to use the install space from what I can tell. But all of the above applies when the workspace is configured for `devel` space.

**Comment by danem** [comment]
@pauldinh thanks for the work.

I've commented out the CompileTest( ... ) lines found in `Groot/test/CmakeLists.txt` and that fixed the build. 

I'm also finding that the Groot executable isn't placed in the install space, but instead in `devel/lib/groot`.

**Comment by pauldinh** [comment]
Great, glad it worked out for you!

The changes in the commit should have addressed the tests as well, not sure why you had to go through the trouble of commenting it out. If you can, a verbose log of your `catkin build` would be helpful.

**Comment by danem** [comment]
Here is the output:

[build.make.033.log](https://github.com/BehaviorTree/Groot/files/4081989/build.make.033.log)

It looks like it cannot link the behaviortree_cpp_v3 library. Perhaps it's because I'm not using the BehaviorTree submodule?

**Comment by facontidavide** [comment]
fixed
