### ISSUE TITLE
Changing tabs in Log Replay crashes

### ISSUE THREAD

**Issue by esromneb** [BehaviorTree/Groot#98]
* Loading a behavior tree log with subtrees will cause a crash if the tabs are clicked.
* Notice in the gif that the subtree closes after the first click of tabs.

# Reproduce:
`BehaforTree.CPP`: 3b30d6a
`Groot`: bd55f24
Run `BehaviorTree.CPP/build/bin/t05_cross_door`
Open Groot and choose Log Replay
Open `BehaviorTree.CPP/build/bin/bt_trace.fbl`
Click `Subtree`, Click `BehaviorTree`, Click `Subtree`, Click `BehaviorTree`
Crash
```
terminate called after throwing an instance of 'std::logic_error'
  what():  subTreeExpand with SUBTREE_REFRESH, but not an expanded SubTree
[1]    28550 abort (core dumped)  ./Groot
```
# GIF of Crash
![groot_crash](https://user-images.githubusercontent.com/919008/93692809-86bbe080-faac-11ea-9288-5cc707907b93.gif)

**Comment by facontidavide** [comment]
I am pretty sure this USED to work. I wonder if any recent PR broke the behavior... I am checking it

**Comment by facontidavide** [comment]
fixed.

Actually, I found a shortcoming in the flatbuffer format, since it doesn't handle gracefully the subtrees. The solution for the time being is to don't create additional tabs.

From a visualiation point of view, showing multiple tabs is also a challenge that I never planned to address, even if I was aware that it would be a nice feature
